const byId = id => document.getElementById(id);
function element(tag, text, className) { const node = document.createElement(tag); if (text !== undefined) node.textContent = text; if (className) node.className = className; return node; }
try {
  const response = await fetch("/api/learning-units", {cache:"no-store"}); const body = await response.json(); if (!response.ok || body.status !== "ready") throw new Error(body.problem?.code ?? "catalog_unavailable");
  for (const unit of body.units) { const card = element("article", undefined, "history"); card.append(element("p", "REVIEWED LEARNING UNIT", "eyebrow"), element("h2", unit.title), element("p", unit.description), element("p", `${unit.reviewed_claims_count} reviewed claims · ${unit.practice_items_count} practice items · ${unit.soak_items_count} soak card`, "mapping-note")); const actions = element("div", undefined, "hero-actions"); const learn = element("a", "開始／繼續閱讀", "primary"); learn.href = `./learn.html?unit=${unit.slug}`; const soak = element("a", "輕鬆再看", "secondary"); soak.href = `./soak.html?unit=${unit.slug}`; const practice = element("a", "直接練習", "secondary"); practice.href = `./practice.html?unit=${unit.slug}`; actions.append(learn, soak, practice); card.append(actions); byId("unit-catalog").append(card); }
  const histories = await Promise.all(body.units.map(async unit => { const attemptResponse = await fetch(`/api/attempts?learning_unit_id=${encodeURIComponent(unit.unit_id)}`, {cache:"no-store"}); const attemptHistory = await attemptResponse.json(); let resume=null; try{const response=await fetch(`/api/resume-contexts?learning_unit_id=${encodeURIComponent(unit.unit_id)}`,{cache:"no-store"});const value=await response.json();if(response.ok)resume=value.context;}catch{} return {unit, attempts: attemptHistory.attempts ?? [], resume}; }));
  const latestResume=histories.filter(item=>item.resume).sort((a,b)=>b.resume.occurred_at.localeCompare(a.resume.occurred_at))[0];
  const latest = histories.flatMap(item => item.attempts.map(attempt => ({...attempt, unit:item.unit}))).sort((a,b) => b.started_at.localeCompare(a.started_at))[0];
  const continuity = byId("continuity"); continuity.replaceChildren(element("h2", "接續學習"));
  if (latestResume) { const context=latestResume.resume; const crumbs=context.structural_breadcrumb.map(item=>item.title).join(" / "); continuity.append(element("p", `上次位置：${latestResume.unit.title} · ${crumbs}`),element("p",context.unresolved_question?`未解：${context.unresolved_question}`:"此位置沒有留下未解問題。","mapping-note")); const link=element("a","回到上次卡住的位置","primary");link.href=`./learn.html?unit=${latestResume.unit.slug}&resume=${encodeURIComponent(context.structural_breadcrumb.at(-1).node_id)}`;continuity.append(link); }
  else if (!latest) continuity.append(element("p", "目前沒有續學點或 Attempt。可以直接選教材閱讀；零筆記、零練習也是合法起點。"));
  else { continuity.append(element("p", `最近 Attempt：${latest.unit.title} · ${latest.activity_type} · ${latest.state}`), element("p", latest.raw_response || "（未輸入文字）", "mapping-note")); const link = element("a", "回到這份教材", "primary"); link.href = `./learn.html?unit=${latest.unit.slug}`; continuity.append(link); }
} catch (error) { byId("continuity").textContent = `Catalog 無法載入：${error.message}`; }
