import {buildExposureRequest, makeId, supportProgression} from "./soak-workspace.js";
const byId=id=>document.getElementById(id); const params=new URLSearchParams(location.search); const slug=params.get("unit")||"os"; const sessionId=makeId("soak"); let unitId; let item;
const now=()=>new Date().toISOString(); let supportSteps=[]; let supportIndex=0;
function renderSupport(){const step=supportSteps[supportIndex];byId("support-stage").textContent=`${supportIndex+1}/${supportSteps.length} · ${step.label}`;byId("support-content").textContent=step.content;byId("next-support").textContent=supportIndex===supportSteps.length-1?"回到熟悉外觀":"換一種支援方式";}
async function record(kind){ const built=buildExposureRequest({eventId:makeId("exposure"),sessionId,unitId,item,kind,occurredAt:now()}); if(built.status!=="ready") throw new Error("invalid exposure"); const response=await fetch("/api/exposures",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(built.request)}); const body=await response.json(); if(!response.ok) throw new Error(body.problem?.code??"exposure unavailable"); return body; }
function showStatus(text){byId("soak-status").textContent=text;}
async function history(){ const response=await fetch(`/api/exposures?learning_unit_id=${encodeURIComponent(unitId)}`,{cache:"no-store"}); const body=await response.json(); const root=byId("exposure-history"); root.replaceChildren(); if(!response.ok){root.textContent="曝光紀錄暫時不可用；仍可閱讀本卡。";return;} const events=body.events??[]; if(!events.length){root.textContent="尚無曝光紀錄。";return;} for(const event of events.slice(0,20)){const p=document.createElement("p");p.className="history-card";p.textContent=`${event.kind} · ${event.occurred_at}`;root.append(p);}}
async function main(){ const response=await fetch(`/api/soak-items?unit=${encodeURIComponent(slug)}`,{cache:"no-store"}); const body=await response.json(); if(!response.ok||body.status!=="ready"||!body.items.length) throw new Error(body.problem?.code??"soak unavailable"); unitId=body.learning_unit_id; item=body.items[0]; const progression=supportProgression(item);if(progression.status!=="ready")throw new Error("invalid support progression");supportSteps=progression.steps; byId("soak-label").textContent=item.label; byId("soak-context").textContent=item.familiar_context; byId("soak-answer").querySelector("h2").textContent=item.answer; byId("practice-later").href=`./practice.html?unit=${encodeURIComponent(slug)}&item=${encodeURIComponent(item.related_practice_item_id)}`;renderSupport(); byId("soak-card").hidden=false; try{await record("presented");showStatus("已記錄呈現；這不是作答。") }catch{showStatus("呈現紀錄暫時不可用；本卡仍可閱讀，不會建立 Attempt。")} await history();}
byId("next-support").addEventListener("click",()=>{supportIndex=(supportIndex+1)%supportSteps.length;renderSupport();});
byId("reveal").addEventListener("click",async()=>{byId("soak-answer").hidden=false;byId("reveal").disabled=true;try{await record("answer_revealed");showStatus("已揭露答案；這不算 retrieval success。") }catch{showStatus("答案已揭露；紀錄暫時不可用。") }await history();});
byId("skip").addEventListener("click",async()=>{try{await record("skipped");showStatus("已滑走。沒有扣分、欠卡或錯誤 Attempt。") }catch{showStatus("已滑走；紀錄暫時不可用，但沒有建立 Attempt。") }await history();});
main().catch(error=>{byId("soak-card").hidden=false;byId("soak-card").innerHTML=`<p class="fatal">Soak 暫時不可用：${error.message}</p>`;});
